### ISSUE TITLE
Facebook Circular Redirect

### ISSUE THREAD

**Issue by max8hine** [batchnz/gatsby-starter-batch-prismic#55]
An issue related with URL trailing path.

![image](https://user-images.githubusercontent.com/15165714/51159130-7a04e380-18ec-11e9-865a-7584eeea6266.png)

[Facebook Debugger](https://developers.facebook.com/tools/debug/sharing)

**Comment by max8hine** [comment]
The issue here is having **301 HTTP Redirect** and turned out that Netlify's pretty URL is causing the issue.

Disable ** Netlify's pretty URL*** solved it.

**Comment by hatzipanis** [comment]
As per our discussion let's leave it as it was @max8hine. Google recommends the 301 to the canonical so Netlify is doing right here.
